# SPDX-License-Identifier: Apache-2.0

name: Build and Upload

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: read-all

jobs:
  update-release:
    name: Update Release
    uses: nubificus/vaccel/.github/workflows/update-release.yml@main
    secrets: inherit
